# Generated by scripts/update-cask.py. The Prerelease cask job refreshes
# version and sha256 after a GitHub prerelease becomes public; edit the script.
cask "deskfuse" do
  version "0.4.0"
  sha256 "3cb382f1a33cc440b937c2b854faa1ff549c171a614dcdecf06b3daedb684098"

  url "https://github.com/GodD6366/deskfuse-release/releases/download/v#{version}/DeskFuse-arm64.dmg"
  name "DeskFuse"
  desc "Clipboard, file transfer and input sharing for trusted devices"
  homepage "https://github.com/GodD6366/deskfuse-release"

  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "DeskFuse.app"
end
