# Generated by scripts/update-cask.py. The Prerelease cask job refreshes
# version and sha256 after a GitHub prerelease becomes public; edit the script.
cask "deskfuse" do
  version "0.4.2"
  sha256 "ab70253eaf940b05a4c5b5478f645d6918eed21ecd7101de4b70f475b628b7ef"

  url "https://github.com/GodD6366/deskfuse-release/releases/download/v#{version}/DeskFuse-arm64.dmg"
  name "DeskFuse"
  desc "Clipboard, file transfer and input sharing for trusted devices"
  homepage "https://github.com/GodD6366/deskfuse-release"

  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "DeskFuse.app"
end
