# Generated by scripts/update-cask.py. The Prerelease cask job refreshes
# version and sha256 after a GitHub prerelease becomes public; edit the script.
cask "deskfuse" do
  version "0.4.5"
  sha256 "b35c38350db6453cfb020d21b4aacd48d9f2f7ca56a524f928625f5f49612687"

  url "https://github.com/GodD6366/deskfuse-release/releases/download/v#{version}/DeskFuse-arm64.dmg"
  name "DeskFuse"
  desc "Clipboard, file transfer and input sharing for trusted devices"
  homepage "https://github.com/GodD6366/deskfuse-release"

  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "DeskFuse.app"
end
