# Generated by scripts/update-cask.py. The Prerelease cask job refreshes
# version and sha256 after a GitHub prerelease becomes public; edit the script.
cask "unidesk" do
  version "0.3.4"
  sha256 "6a17177b2adb32eca20fdc5ca837787e5327ed2da8dedc031d9f5a092cdbb017"

  url "https://github.com/GodD6366/unidesk-release/releases/download/v#{version}/uniDesk-arm64.dmg"
  name "uniDesk"
  desc "Clipboard, file transfer and input sharing for trusted devices"
  homepage "https://github.com/GodD6366/unidesk-release"

  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "uniDesk.app"
end
