# Generated by scripts/update-cask.py. The Prerelease cask job refreshes
# version and sha256 after a GitHub prerelease becomes public; edit the script.
cask "unidesk" do
  version "0.3.2"
  sha256 "22d65dcc14cc0fab6a21226976ed4c2a3fc6da802021b8afb40bd4ea18a0fef1"

  url "https://github.com/GodD6366/unidesk-release/releases/download/v#{version}/uniDesk-arm64.dmg"
  name "uniDesk"
  desc "Clipboard, file transfer and input sharing for trusted devices"
  homepage "https://github.com/GodD6366/unidesk-release"

  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "uniDesk.app"
end
